/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafegui;

import java.awt.CardLayout;
import java.sql.*;
import javax.swing.*;;

/**
 *
 * @author User
 */
public class Edit extends javax.swing.JFrame {
    
    String user = "root";
    String pswd = "";
    String host = "localhost";
    String db = "cafe";
    String url = "";
    String StrSQL;
    private Connection Lconnection = null;
    private CardLayout cardLayout;
    
    public Edit() {
        initComponents();
        btnEditMakan.setEnabled(false);
        btnEditMinum.setEnabled(false);
        btnEditLain.setEnabled(false);
        btnHapusMakan.setEnabled(false);
        btnHapusMinum.setEnabled(false);
        btnHapusLain.setEnabled(false);
        
        cardLayout = (CardLayout) jPanel2.getLayout();
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            url="jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pswd;
            Lconnection = DriverManager.getConnection(url);
        }
        catch (ClassNotFoundException e){
            System.out.println("jdbc.Driver tidak ditemukan");
        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boxUbahDBMenu = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        txtIDMinumTambah = new javax.swing.JTextField();
        txtNamaMinumTambah = new javax.swing.JTextField();
        txtHrgMinumTambah = new javax.swing.JTextField();
        btnSimpanMinum = new javax.swing.JButton();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        btnCekMenuMinuman = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        txtIDMakanTambah = new javax.swing.JTextField();
        txtNamaMakanTambah = new javax.swing.JTextField();
        txtHrgMakanTambah = new javax.swing.JTextField();
        btnSimpanMakan = new javax.swing.JButton();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        btnCekMenuMakanan = new javax.swing.JButton();
        jLabel90 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        txtIDLainTambah = new javax.swing.JTextField();
        txtNamaLainTambah = new javax.swing.JTextField();
        txtHrgLainTambah = new javax.swing.JTextField();
        btnSimpanLain = new javax.swing.JButton();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btnCekMenuLain = new javax.swing.JButton();
        jLabel98 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        txtIDMinumEdit = new javax.swing.JTextField();
        txtNamaMinumEdit = new javax.swing.JTextField();
        txtHrgMinumEdit = new javax.swing.JTextField();
        btnIDMinumEdit = new javax.swing.JButton();
        btnEditMinum = new javax.swing.JButton();
        jLabel109 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        btnCekMenuMakanan2 = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        txtIDMakanEdit = new javax.swing.JTextField();
        txtNamaMakanEdit = new javax.swing.JTextField();
        txtHrgMakanEdit = new javax.swing.JTextField();
        btnIDMakanEdit = new javax.swing.JButton();
        btnEditMakan = new javax.swing.JButton();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        btnCekMenuMakanan1 = new javax.swing.JButton();
        jLabel94 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        txtIDLainEdit = new javax.swing.JTextField();
        txtNamaLainEdit = new javax.swing.JTextField();
        txtHrgLainEdit = new javax.swing.JTextField();
        btnIDLainEdit = new javax.swing.JButton();
        btnEditLain = new javax.swing.JButton();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        btnCekMenuMakanan4 = new javax.swing.JButton();
        jLabel102 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        txtIDMinumHapus = new javax.swing.JTextField();
        txtNamaMinumHapus = new javax.swing.JTextField();
        txtHrgMinumHapus = new javax.swing.JTextField();
        btnIDMinumHapus = new javax.swing.JButton();
        btnHapusMinum = new javax.swing.JButton();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        btnCekMenuMakanan5 = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        txtIDMakanHapus = new javax.swing.JTextField();
        jLabel103 = new javax.swing.JLabel();
        txtNamaMakanHapus = new javax.swing.JTextField();
        jLabel104 = new javax.swing.JLabel();
        txtHrgMakanHapus = new javax.swing.JTextField();
        btnIDMakanHapus = new javax.swing.JButton();
        btnHapusMakan = new javax.swing.JButton();
        btnCekMenuMakanan3 = new javax.swing.JButton();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        txtIDLainHapus = new javax.swing.JTextField();
        txtNamaLainHapus = new javax.swing.JTextField();
        txtHrgLainHapus = new javax.swing.JTextField();
        btnIDLainHapus = new javax.swing.JButton();
        btnHapusLain = new javax.swing.JButton();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        btnCekMenuMakanan6 = new javax.swing.JButton();
        jLabel110 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 88, 168));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        boxUbahDBMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tambah Menu", "Edit Menu", "Hapus Menu" }));
        boxUbahDBMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxUbahDBMenuActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(248, 251, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel16.setBackground(new java.awt.Color(248, 251, 255));

        jPanel23.setBackground(new java.awt.Color(248, 251, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDMinumTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaMinumTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgMinumTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnSimpanMinum.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnSimpanMinum.setText("Simpan");
        btnSimpanMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanMinumActionPerformed(evt);
            }
        });

        jLabel120.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel120.setText("ID Menu (2001)");

        jLabel121.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel121.setText("Nama Menu");

        jLabel50.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel50.setText("Harga Menu");

        btnCekMenuMinuman.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMinuman.setText("Cek Menu");
        btnCekMenuMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMinumanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel120, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel121, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDMinumTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMinumTambah)
                    .addComponent(txtHrgMinumTambah))
                .addGap(18, 18, 18)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpanMinum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCekMenuMinuman, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDMinumTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpanMinum, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel120))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMinumTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel121)
                    .addComponent(btnCekMenuMinuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgMinumTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(248, 251, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDMakanTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaMakanTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgMakanTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnSimpanMakan.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnSimpanMakan.setText("Simpan");
        btnSimpanMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanMakanActionPerformed(evt);
            }
        });

        jLabel118.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel118.setText("ID Menu (1001)");

        jLabel119.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel119.setText("Nama Menu");

        jLabel49.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel49.setText("Harga Menu");

        btnCekMenuMakanan.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMakanan.setText("Cek Menu");
        btnCekMenuMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMakananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel118, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel119, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDMakanTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMakanTambah)
                    .addComponent(txtHrgMakanTambah))
                .addGap(18, 18, 18)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpanMakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCekMenuMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDMakanTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpanMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel118))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMakanTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel119)
                    .addComponent(btnCekMenuMakanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgMakanTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel90.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel90.setText("Makanan");

        jLabel92.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel92.setText("Minuman");

        jPanel25.setBackground(new java.awt.Color(248, 251, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDLainTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaLainTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgLainTambah.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnSimpanLain.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnSimpanLain.setText("Simpan");
        btnSimpanLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanLainActionPerformed(evt);
            }
        });

        jLabel122.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel122.setText("ID Menu (3001)");

        jLabel123.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel123.setText("Nama Menu");

        jLabel51.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel51.setText("Harga Menu");

        btnCekMenuLain.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuLain.setText("Cek Menu");
        btnCekMenuLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuLainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel122, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel123, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDLainTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaLainTambah)
                    .addComponent(txtHrgLainTambah))
                .addGap(18, 18, 18)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekMenuLain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpanLain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDLainTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpanLain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel122))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaLainTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel123)
                    .addComponent(btnCekMenuLain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgLainTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel98.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel98.setText("Lain-lain");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel90)
                    .addComponent(jLabel98)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel92))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel90)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel92)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel98)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, "card2");

        jPanel17.setBackground(new java.awt.Color(248, 251, 255));

        jPanel26.setBackground(new java.awt.Color(248, 251, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDMinumEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaMinumEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgMinumEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnIDMinumEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnIDMinumEdit.setText("Cek ID");
        btnIDMinumEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDMinumEditActionPerformed(evt);
            }
        });

        btnEditMinum.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnEditMinum.setText("Edit");
        btnEditMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMinumActionPerformed(evt);
            }
        });

        jLabel109.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel109.setText("ID Menu");

        jLabel115.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel115.setText("Nama Menu");

        jLabel47.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel47.setText("Harga Menu");

        btnCekMenuMakanan2.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMakanan2.setText("Cek Menu");
        btnCekMenuMakanan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMakanan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel115, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDMinumEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMinumEdit)
                    .addComponent(txtHrgMinumEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekMenuMakanan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditMinum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIDMinumEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDMinumEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel109)
                    .addComponent(btnIDMinumEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMinumEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel115)
                    .addComponent(btnEditMinum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgMinumEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47)
                    .addComponent(btnCekMenuMakanan2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel27.setBackground(new java.awt.Color(248, 251, 255));
        jPanel27.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDMakanEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaMakanEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgMakanEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnIDMakanEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnIDMakanEdit.setText("Cek ID");
        btnIDMakanEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDMakanEditActionPerformed(evt);
            }
        });

        btnEditMakan.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnEditMakan.setText("Edit");
        btnEditMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditMakanActionPerformed(evt);
            }
        });

        jLabel107.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel107.setText("ID Menu");

        jLabel108.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel108.setText("Nama Menu");

        jLabel46.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel46.setText("Harga Menu");

        btnCekMenuMakanan1.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMakanan1.setText("Cek Menu");
        btnCekMenuMakanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMakanan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDMakanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMakanEdit)
                    .addComponent(txtHrgMakanEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekMenuMakanan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditMakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIDMakanEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDMakanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel107)
                    .addComponent(btnIDMakanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMakanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel108)
                    .addComponent(btnEditMakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgMakanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46)
                    .addComponent(btnCekMenuMakanan1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel94.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel94.setText("Makanan");

        jLabel97.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel97.setText("Minuman");

        jPanel28.setBackground(new java.awt.Color(248, 251, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDLainEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaLainEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgLainEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnIDLainEdit.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnIDLainEdit.setText("Cek ID");
        btnIDLainEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDLainEditActionPerformed(evt);
            }
        });

        btnEditLain.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnEditLain.setText("Edit");
        btnEditLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditLainActionPerformed(evt);
            }
        });

        jLabel116.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel116.setText("ID Menu");

        jLabel117.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel117.setText("Nama Menu");

        jLabel48.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel48.setText("Harga Menu");

        btnCekMenuMakanan4.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMakanan4.setText("Cek Menu");
        btnCekMenuMakanan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMakanan4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel116, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel117, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDLainEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaLainEdit)
                    .addComponent(txtHrgLainEdit))
                .addGap(18, 18, 18)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekMenuMakanan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditLain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIDLainEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDLainEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel116)
                    .addComponent(btnIDLainEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaLainEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel117)
                    .addComponent(btnEditLain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgLainEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(btnCekMenuMakanan4))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel102.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel102.setText("Lain-lain");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel94, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel97, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel102, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel94)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel97)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, "card3");

        jPanel18.setBackground(new java.awt.Color(248, 251, 255));

        jPanel29.setBackground(new java.awt.Color(248, 251, 255));
        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDMinumHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaMinumHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgMinumHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnIDMinumHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnIDMinumHapus.setText("Cek ID");
        btnIDMinumHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDMinumHapusActionPerformed(evt);
            }
        });

        btnHapusMinum.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnHapusMinum.setText("Hapus");
        btnHapusMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMinumActionPerformed(evt);
            }
        });

        jLabel111.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel111.setText("ID Menu");

        jLabel112.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel112.setText("Nama Menu");

        jLabel44.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel44.setText("Harga Menu");

        btnCekMenuMakanan5.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMakanan5.setText("Cek Menu");
        btnCekMenuMakanan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMakanan5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel111, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel112, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDMinumHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaMinumHapus)
                    .addComponent(txtHrgMinumHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekMenuMakanan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusMinum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIDMinumHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDMinumHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel111))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaMinumHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel112))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHrgMinumHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addComponent(btnIDMinumHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusMinum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCekMenuMakanan5)
                        .addGap(10, 10, 10))))
        );

        jPanel30.setBackground(new java.awt.Color(248, 251, 255));
        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel43.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel43.setText("Harga Menu");

        txtIDMakanHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        jLabel103.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel103.setText("Nama Menu");

        txtNamaMakanHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        jLabel104.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel104.setText("ID Menu");

        txtHrgMakanHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnIDMakanHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnIDMakanHapus.setText("Cek ID");
        btnIDMakanHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDMakanHapusActionPerformed(evt);
            }
        });

        btnHapusMakan.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnHapusMakan.setText("Hapus");
        btnHapusMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMakanActionPerformed(evt);
            }
        });

        btnCekMenuMakanan3.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMakanan3.setText("Cek Menu");
        btnCekMenuMakanan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMakanan3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDMakanHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHrgMakanHapus)
                            .addComponent(txtNamaMakanHapus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekMenuMakanan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusMakan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIDMakanHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDMakanHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIDMakanHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel104))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMakanHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel103)
                    .addComponent(btnHapusMakan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHrgMakanHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel43)
                    .addComponent(btnCekMenuMakanan3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel105.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel105.setText("Makanan");

        jLabel106.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel106.setText("Minuman");

        jPanel31.setBackground(new java.awt.Color(248, 251, 255));
        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtIDLainHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtNamaLainHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        txtHrgLainHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N

        btnIDLainHapus.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnIDLainHapus.setText("Cek ID");
        btnIDLainHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIDLainHapusActionPerformed(evt);
            }
        });

        btnHapusLain.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnHapusLain.setText("Hapus");
        btnHapusLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusLainActionPerformed(evt);
            }
        });

        jLabel113.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel113.setText("ID Menu");

        jLabel114.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel114.setText("Nama Menu");

        jLabel45.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel45.setText("Harga Menu");

        btnCekMenuMakanan6.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        btnCekMenuMakanan6.setText("Cek Menu");
        btnCekMenuMakanan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekMenuMakanan6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel113, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIDLainHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaLainHapus)
                    .addComponent(txtHrgLainHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCekMenuMakanan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapusLain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIDLainHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIDLainHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel31Layout.createSequentialGroup()
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIDLainHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel113))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaLainHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel114)
                            .addComponent(btnHapusLain, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHrgLainHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45)
                            .addComponent(btnCekMenuMakanan6))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel110.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 14)); // NOI18N
        jLabel110.setText("Lain-lain");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel105, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel106, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel110, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel105)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel106)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel110)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boxUbahDBMenu, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxUbahDBMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxUbahDBMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxUbahDBMenuActionPerformed
        String Itu = boxUbahDBMenu.getSelectedItem().toString();
        if (Itu.equals("Tambah Menu")) {
            cardLayout.show(jPanel2, "card2");
        } else if (Itu.equals("Edit Menu")) {
            cardLayout.show(jPanel2, "card3");
        } else if (Itu.equals("Hapus Menu")) {
            cardLayout.show(jPanel2, "card4");
        }        
    }//GEN-LAST:event_boxUbahDBMenuActionPerformed

    
    //Tambah
    
    
    private void btnSimpanMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanMakanActionPerformed
        try{
            StrSQL = "INSERT INTO makanan (ID_Makanan, Nama_Makanan, Harga_Makanan)"
                   + "VALUES (?,?,?)";
        
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);
            
            pStatement.setString(1, txtIDMakanTambah.getText());
            pStatement.setString(2, txtNamaMakanTambah.getText());
            pStatement.setString(3, txtHrgMakanTambah.getText());
            

            if (pStatement.executeUpdate()>0){
                JOptionPane.showMessageDialog(this,
                    "Penambahan sukses", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,
                    "Penambahan gagal", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();
            
            txtNamaMakanTambah.setText("");
            txtHrgMakanTambah.setText("");
            txtIDMakanTambah.setText("");


        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnSimpanMakanActionPerformed

    private void btnCekMenuMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMakananActionPerformed
        new CekMenuMakanan().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMakananActionPerformed

    private void btnSimpanMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanMinumActionPerformed
        try{
            StrSQL = "INSERT INTO minuman (ID_Minuman, Nama_Minuman, Harga_Minuman)"
                   + "VALUES (?,?,?)";
        
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);
            
            pStatement.setString(1, txtIDMinumTambah.getText());
            pStatement.setString(2, txtNamaMinumTambah.getText());
            pStatement.setString(3, txtHrgMinumTambah.getText());
            

            if (pStatement.executeUpdate()>0){
                JOptionPane.showMessageDialog(this,
                    "Penambahan sukses", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,
                    "Penambahan gagal", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();
            
            txtNamaMinumTambah.setText("");
            txtHrgMinumTambah.setText("");
            txtIDMinumTambah.setText("");

        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnSimpanMinumActionPerformed

    private void btnCekMenuMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMinumanActionPerformed
        new CekMenuMinuman().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMinumanActionPerformed

    private void btnSimpanLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanLainActionPerformed
        try{
            StrSQL = "INSERT INTO MenuLain (ID_Menu, Nama_Menu, Harga_Menu)"
                   + "VALUES (?,?,?)";
        
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);
            
            pStatement.setString(1, txtIDLainTambah.getText());
            pStatement.setString(2, txtNamaLainTambah.getText());
            pStatement.setString(3, txtHrgLainTambah.getText());
            

            if (pStatement.executeUpdate()>0){
                JOptionPane.showMessageDialog(this,
                    "Penambahan sukses", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,
                    "Penambahan gagal", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();
            
            txtNamaLainTambah.setText("");
            txtHrgLainTambah.setText("");
            txtIDLainTambah.setText("");

        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnSimpanLainActionPerformed

    private void btnCekMenuLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuLainActionPerformed
        new CekMenuLain().setVisible(true);
    }//GEN-LAST:event_btnCekMenuLainActionPerformed

    
    // Edit
    
   
    private void btnIDMakanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDMakanEditActionPerformed
        try {
            StrSQL = "SELECT * FROM makanan WHERE ID_Makanan ='" + txtIDMakanEdit.getText() + "'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaMakanEdit.setText(rs.getString("Nama_Makanan"));
                txtHrgMakanEdit.setText(rs.getString("Harga_Makanan"));
                txtIDMakanEdit.setText(rs.getString("ID_Makanan"));

                btnEditMakan.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Tidak Ada", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnIDMakanEditActionPerformed

    private void btnIDMinumEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDMinumEditActionPerformed
        try {
            StrSQL = "SELECT * FROM minuman WHERE ID_Minuman ='" + txtIDMinumEdit.getText() + "'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaMinumEdit.setText(rs.getString("Nama_Minuman"));
                txtHrgMinumEdit.setText(rs.getString("Harga_Minuman"));
                txtIDMinumEdit.setText(rs.getString("ID_Minuman"));

                btnEditMinum.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Tidak Ada", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnIDMinumEditActionPerformed

    private void btnIDLainEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDLainEditActionPerformed
        try {
            StrSQL = "SELECT * FROM MenuLain WHERE ID_Menu ='" + txtIDLainEdit.getText() + "'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaLainEdit.setText(rs.getString("Nama_Menu"));
                txtHrgLainEdit.setText(rs.getString("Harga_Menu"));
                txtIDLainEdit.setText(rs.getString("ID_Menu"));

                btnEditLain.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Tidak Ada", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnIDLainEditActionPerformed

    private void btnEditMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMakanActionPerformed
        try {
            StrSQL = "UPDATE makanan SET Nama_Makanan = ?, Harga_Makanan = ? WHERE ID_Makanan = ?";
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);

            pStatement.setString(1, txtNamaMakanEdit.getText());
            pStatement.setString(2, txtHrgMakanEdit.getText());
            pStatement.setString(3, txtIDMakanEdit.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Edit sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Edit gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();

            txtNamaMakanEdit.setText("");
            txtHrgMakanEdit.setText("");
            txtIDMakanEdit.setText("");
            
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnEditMakanActionPerformed

    private void btnEditMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditMinumActionPerformed
        try {
            StrSQL = "UPDATE minuman SET Nama_Minuman = ?, Harga_Minuman = ? WHERE ID_Minuman = ?";
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);

            pStatement.setString(1, txtNamaMinumEdit.getText());
            pStatement.setString(2, txtHrgMinumEdit.getText());
            pStatement.setString(3, txtIDMinumEdit.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Edit sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Edit gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();

            txtNamaMinumEdit.setText("");
            txtHrgMinumEdit.setText("");
            txtIDMinumEdit.setText("");
            
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnEditMinumActionPerformed

    private void btnEditLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditLainActionPerformed
        try {
            StrSQL = "UPDATE MenuLain SET Nama_Menu = ?, Harga_Menu = ? WHERE ID_Menu = ?";
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);

            pStatement.setString(1, txtNamaLainEdit.getText());
            pStatement.setString(2, txtHrgLainEdit.getText());
            pStatement.setString(3, txtIDLainEdit.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Edit sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Edit gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();

            txtNamaLainEdit.setText("");
            txtHrgLainEdit.setText("");
            txtIDLainEdit.setText("");
            
        } catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnEditLainActionPerformed

    private void btnCekMenuMakanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMakanan1ActionPerformed
        new CekMenuMakanan().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMakanan1ActionPerformed

    private void btnCekMenuMakanan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMakanan2ActionPerformed
        new CekMenuMinuman().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMakanan2ActionPerformed

    private void btnCekMenuMakanan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMakanan4ActionPerformed
        new CekMenuLain().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMakanan4ActionPerformed

    
    
    //Hapus
    
    private void btnIDMakanHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDMakanHapusActionPerformed
        try {
            StrSQL = "SELECT * FROM makanan WHERE ID_Makanan ='" + txtIDMakanHapus.getText() + "'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaMakanHapus.setText(rs.getString("Nama_Makanan"));
                txtHrgMakanHapus.setText(rs.getString("Harga_Makanan"));
                txtIDMakanHapus.setText(rs.getString("ID_Makanan"));

                btnHapusMakan.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Tidak Ada", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnIDMakanHapusActionPerformed

    private void btnIDMinumHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDMinumHapusActionPerformed
        try {
            StrSQL = "SELECT * FROM minuman WHERE ID_Minuman ='" + txtIDMinumHapus.getText() + "'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaMinumHapus.setText(rs.getString("Nama_Minuman"));
                txtHrgMinumHapus.setText(rs.getString("Harga_Minuman"));
                txtIDMinumHapus.setText(rs.getString("ID_Minuman"));

                btnHapusMinum.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Tidak Ada", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnIDMinumHapusActionPerformed

    private void btnIDLainHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIDLainHapusActionPerformed
        try {
            StrSQL = "SELECT * FROM MenuLain WHERE ID_Menu ='" + txtIDLainHapus.getText() + "'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaLainHapus.setText(rs.getString("Nama_Menu"));
                txtHrgLainHapus.setText(rs.getString("Harga_Menu"));
                txtIDLainHapus.setText(rs.getString("ID_Menu"));

                btnHapusLain.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                    "Data Tidak Ada", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
        }
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnIDLainHapusActionPerformed

    private void btnHapusMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMakanActionPerformed
        try{
            StrSQL = "DELETE FROM makanan WHERE ID_Makanan = ?";
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);

            pStatement.setString(1, txtIDMakanHapus.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();

            txtIDMakanHapus.setText("");
            txtNamaMakanHapus.setText("");
            txtHrgMakanHapus.setText("");
        }
        catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnHapusMakanActionPerformed

    private void btnHapusMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMinumActionPerformed
        try{
            StrSQL = "DELETE FROM minuman WHERE ID_Minuman = ?";
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);

            pStatement.setString(1, txtIDMinumHapus.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();

            txtIDMinumHapus.setText("");
            txtNamaMinumHapus.setText("");
            txtHrgMinumHapus.setText("");
        }
        catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnHapusMinumActionPerformed

    private void btnHapusLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusLainActionPerformed
        try{
            StrSQL = "DELETE FROM MenuLain WHERE ID_Menu = ?";
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);

            pStatement.setString(1, txtIDMinumHapus.getText());

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();

            txtIDLainHapus.setText("");
            txtNamaLainHapus.setText("");
            txtHrgLainHapus.setText("");
        }
        catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        }
    }//GEN-LAST:event_btnHapusLainActionPerformed

    private void btnCekMenuMakanan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMakanan3ActionPerformed
        new CekMenuMakanan().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMakanan3ActionPerformed

    private void btnCekMenuMakanan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMakanan5ActionPerformed
        new CekMenuMinuman().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMakanan5ActionPerformed

    private void btnCekMenuMakanan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekMenuMakanan6ActionPerformed
        new CekMenuLain().setVisible(true);
    }//GEN-LAST:event_btnCekMenuMakanan6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxUbahDBMenu;
    private javax.swing.JButton btnCekMenuLain;
    private javax.swing.JButton btnCekMenuMakanan;
    private javax.swing.JButton btnCekMenuMakanan1;
    private javax.swing.JButton btnCekMenuMakanan2;
    private javax.swing.JButton btnCekMenuMakanan3;
    private javax.swing.JButton btnCekMenuMakanan4;
    private javax.swing.JButton btnCekMenuMakanan5;
    private javax.swing.JButton btnCekMenuMakanan6;
    private javax.swing.JButton btnCekMenuMinuman;
    private javax.swing.JButton btnEditLain;
    private javax.swing.JButton btnEditMakan;
    private javax.swing.JButton btnEditMinum;
    private javax.swing.JButton btnHapusLain;
    private javax.swing.JButton btnHapusMakan;
    private javax.swing.JButton btnHapusMinum;
    private javax.swing.JButton btnIDLainEdit;
    private javax.swing.JButton btnIDLainHapus;
    private javax.swing.JButton btnIDMakanEdit;
    private javax.swing.JButton btnIDMakanHapus;
    private javax.swing.JButton btnIDMinumEdit;
    private javax.swing.JButton btnIDMinumHapus;
    private javax.swing.JButton btnSimpanLain;
    private javax.swing.JButton btnSimpanMakan;
    private javax.swing.JButton btnSimpanMinum;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txtHrgLainEdit;
    private javax.swing.JTextField txtHrgLainHapus;
    private javax.swing.JTextField txtHrgLainTambah;
    private javax.swing.JTextField txtHrgMakanEdit;
    private javax.swing.JTextField txtHrgMakanHapus;
    private javax.swing.JTextField txtHrgMakanTambah;
    private javax.swing.JTextField txtHrgMinumEdit;
    private javax.swing.JTextField txtHrgMinumHapus;
    private javax.swing.JTextField txtHrgMinumTambah;
    private javax.swing.JTextField txtIDLainEdit;
    private javax.swing.JTextField txtIDLainHapus;
    private javax.swing.JTextField txtIDLainTambah;
    private javax.swing.JTextField txtIDMakanEdit;
    private javax.swing.JTextField txtIDMakanHapus;
    private javax.swing.JTextField txtIDMakanTambah;
    private javax.swing.JTextField txtIDMinumEdit;
    private javax.swing.JTextField txtIDMinumHapus;
    private javax.swing.JTextField txtIDMinumTambah;
    private javax.swing.JTextField txtNamaLainEdit;
    private javax.swing.JTextField txtNamaLainHapus;
    private javax.swing.JTextField txtNamaLainTambah;
    private javax.swing.JTextField txtNamaMakanEdit;
    private javax.swing.JTextField txtNamaMakanHapus;
    private javax.swing.JTextField txtNamaMakanTambah;
    private javax.swing.JTextField txtNamaMinumEdit;
    private javax.swing.JTextField txtNamaMinumHapus;
    private javax.swing.JTextField txtNamaMinumTambah;
    // End of variables declaration//GEN-END:variables
}
