/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafegui;

import java.sql.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;

public class InputOrder extends javax.swing.JFrame {
    public double finalTotal = 0.0;
    public double fintotMakan = 0.0;
    public double fintotMinum = 0.0;
    public double fintotLain = 0.0;
    
    String user = "root";
    String pswd = "";
    String host = "localhost";
    String db = "cafe";
    String url = "";
    String StrSQL;
    private Connection Lconnection = null;
    
    public InputOrder() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            url="jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pswd;
            Lconnection = DriverManager.getConnection(url);
        }
        catch (ClassNotFoundException e){
            System.out.println("jdbc.Driver tidak ditemukan");
        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTampilInp = new javax.swing.JTextArea();
        txtNamaInp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        boxJenisInp = new javax.swing.JComboBox<>();
        boxNomorInp = new javax.swing.JComboBox<>();
        boxMakanInp = new javax.swing.JComboBox<>();
        boxMinumInp = new javax.swing.JComboBox<>();
        boxLainInp = new javax.swing.JComboBox<>();
        btnHapusInp = new javax.swing.JButton();
        btnCetakInp = new javax.swing.JButton();
        spinMakanInp = new javax.swing.JSpinner();
        btnTambahMakan = new javax.swing.JButton();
        spinMinumInp = new javax.swing.JSpinner();
        btnTambahMinum = new javax.swing.JButton();
        spinLainInp = new javax.swing.JSpinner();
        btnTambahLain = new javax.swing.JButton();
        btnOrderPend = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 88, 168));

        jButton1.setBackground(new java.awt.Color(10, 88, 168));
        jButton1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(248, 251, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setText(":");

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel4.setText("Jenis Meja ");

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel5.setText("No. Meja ");

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel6.setText("Makanan");

        jLabel7.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel7.setText("Minuman");

        jLabel8.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel8.setText("Lain-lain");

        jLabel9.setFont(new java.awt.Font("Montserrat", 1, 20)); // NOI18N
        jLabel9.setText("Output");

        areaTampilInp.setColumns(20);
        areaTampilInp.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        areaTampilInp.setRows(5);
        jScrollPane1.setViewportView(areaTampilInp);

        jLabel10.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel10.setText("Nama Customer");

        jLabel11.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel11.setText(":");

        jLabel12.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel12.setText(":");

        jLabel13.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel13.setText(":");

        jLabel14.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel14.setText(":");

        jLabel15.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel15.setText(":");

        boxJenisInp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Normal", "VIP" }));
        boxJenisInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxJenisInpActionPerformed(evt);
            }
        });

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            url="jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pswd;
            Connection conn = DriverManager.getConnection(url);

            String sql = "SELECT Nama_Makanan, Harga_Makanan FROM makanan";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String namaMakanan = rs.getString("Nama_Makanan");
                boxMakanInp.addItem(namaMakanan);
            }

            rs.close();
            stmt.close();

        }catch (ClassNotFoundException e){
            System.out.println("jdbc.Driver tidak ditemukan");

        }catch (SQLException ex) {
            ex.printStackTrace();
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            url="jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pswd;
            Connection conn = DriverManager.getConnection(url);

            String sql = "SELECT Nama_Minuman FROM minuman";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String namaMinuman = rs.getString("Nama_Minuman");
                boxMinumInp.addItem(namaMinuman);
            }

            rs.close();
            stmt.close();

        }catch (ClassNotFoundException e){
            System.out.println("jdbc.Driver tidak ditemukan");

        }catch (SQLException ex) {
            ex.printStackTrace();
        }

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");

            url="jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pswd;
            Connection conn = DriverManager.getConnection(url);

            String sql = "SELECT Nama_Menu FROM MenuLain";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                String namaMenuLain = rs.getString("Nama_Menu");
                boxLainInp.addItem(namaMenuLain);
            }

            rs.close();
            stmt.close();

        }catch (ClassNotFoundException e){
            System.out.println("jdbc.Driver tidak ditemukan");

        }catch (SQLException ex) {
            ex.printStackTrace();
        }

        btnHapusInp.setText("Hapus Semua");
        btnHapusInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusInpActionPerformed(evt);
            }
        });

        btnCetakInp.setText("Cetak");
        btnCetakInp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakInpActionPerformed(evt);
            }
        });

        spinMakanInp.setValue(1);

        btnTambahMakan.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnTambahMakan.setText("+");
        btnTambahMakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMakanActionPerformed(evt);
            }
        });

        spinMinumInp.setValue(1);

        btnTambahMinum.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnTambahMinum.setText("+");
        btnTambahMinum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMinumActionPerformed(evt);
            }
        });

        spinLainInp.setValue(1);

        btnTambahLain.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        btnTambahLain.setText("+");
        btnTambahLain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahLainActionPerformed(evt);
            }
        });

        btnOrderPend.setText("Cek Pending");
        btnOrderPend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderPendActionPerformed(evt);
            }
        });

        btnOrderHistory.setText("Cek History");
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaInp, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(boxMinumInp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxMakanInp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxNomorInp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxJenisInp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(boxLainInp, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(spinMakanInp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTambahMakan))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(spinLainInp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTambahLain))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(spinMinumInp, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTambahMinum)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHapusInp, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(btnCetakInp, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(btnOrderPend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrderHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(txtNamaInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(boxJenisInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(boxNomorInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(boxMakanInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinMakanInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambahMakan)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(boxMinumInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinMinumInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambahMinum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boxLainInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(spinLainInp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnTambahLain)))
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnHapusInp)
                        .addGap(18, 18, 18)
                        .addComponent(btnCetakInp)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrderPend)
                        .addGap(18, 18, 18)
                        .addComponent(btnOrderHistory)
                        .addGap(50, 50, 50))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusInpActionPerformed
        areaTampilInp.setText(null);
    }//GEN-LAST:event_btnHapusInpActionPerformed

    private void btnCetakInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakInpActionPerformed
        String JenisInp = boxJenisInp.getSelectedItem().toString();
        String noMejaInp = boxNomorInp.getSelectedItem().toString();
        String txtAreaInp = areaTampilInp.getText();
        
        finalTotal = fintotMakan + fintotMinum + fintotLain;
        String fintot = String.valueOf(finalTotal);
                
                
        Order_info oi = new Order_info();
        oi.lblNamaInp.setText(txtNamaInp.getText());
        oi.lblJenisInp.setText(JenisInp);
        oi.lblNomorInp.setText(noMejaInp);
        oi.areaBon.setText(txtAreaInp);
        oi.lblTotalInp.setText(fintot);
        
        oi.setVisible(true);
    }//GEN-LAST:event_btnCetakInpActionPerformed

    private void btnTambahMakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMakanActionPerformed
        
        String selectedMakanan = (String) boxMakanInp.getSelectedItem();
        
        try {
            String sql = "SELECT Harga_Makanan FROM makanan WHERE Nama_Makanan=?";
            PreparedStatement pstmt = Lconnection.prepareStatement(sql);
            pstmt.setString(1, selectedMakanan);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                double hargaMakanan = rs.getDouble("Harga_Makanan");
                int quantity = (int) spinMakanInp.getValue();
                double totalMakan = hargaMakanan * quantity;
                areaTampilInp.append(selectedMakanan + "\t" + "x"+quantity + "\t" + totalMakan + "\n");
                fintotMakan += totalMakan;
                
            }

            rs.close();
            pstmt.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnTambahMakanActionPerformed

    private void btnTambahMinumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMinumActionPerformed
        String selectedMinuman = (String) boxMinumInp.getSelectedItem();
        
        try {
            String sql = "SELECT Harga_Minuman FROM minuman WHERE Nama_Minuman=?";
            PreparedStatement pstmt = Lconnection.prepareStatement(sql);
            pstmt.setString(1, selectedMinuman);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                double hargaMinuman = rs.getDouble("Harga_Minuman");
                int quantity = (int) spinMinumInp.getValue();
                double totalMinum = hargaMinuman * quantity;
                areaTampilInp.append(selectedMinuman + "\t" + "x"+quantity + "\t" + totalMinum + "\n");
                fintotMinum += totalMinum;
                
            }

            rs.close();
            pstmt.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnTambahMinumActionPerformed

    private void btnTambahLainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahLainActionPerformed
        String selectedLain = (String) boxLainInp.getSelectedItem();
        
        try {
            String sql = "SELECT Harga_Menu FROM MenuLain WHERE Nama_Menu=?";
            PreparedStatement pstmt = Lconnection.prepareStatement(sql);
            pstmt.setString(1, selectedLain);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                double hargaLain = rs.getDouble("Harga_Menu");
                int quantity = (int) spinLainInp.getValue();
                double totalLain = hargaLain * quantity;
                areaTampilInp.append(selectedLain + "\t" + "x"+quantity + "\t" + totalLain + "\n");
                fintotLain += totalLain;
                
            }

            rs.close();
            pstmt.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnTambahLainActionPerformed

    private void btnOrderPendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderPendActionPerformed
        new OrderPending().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderPendActionPerformed

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        new OrderHistory().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    private void boxJenisInpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxJenisInpActionPerformed
        String selectedCategory = boxJenisInp.getSelectedItem().toString();
            if ("Normal".equals(selectedCategory)) {
                boxNomorInp.removeAllItems();
                boxNomorInp.addItem("1");
                boxNomorInp.addItem("3");
                boxNomorInp.addItem("5");
                boxNomorInp.addItem("7");
                boxNomorInp.addItem("9");
                
            } else if ("VIP".equals(selectedCategory)) {
                boxNomorInp.removeAllItems();
                boxNomorInp.addItem("2");
                boxNomorInp.addItem("4");
                boxNomorInp.addItem("6");
                boxNomorInp.addItem("8");
                boxNomorInp.addItem("10");
            }
    }//GEN-LAST:event_boxJenisInpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTampilInp;
    private javax.swing.JComboBox<String> boxJenisInp;
    private javax.swing.JComboBox<String> boxLainInp;
    private javax.swing.JComboBox<String> boxMakanInp;
    private javax.swing.JComboBox<String> boxMinumInp;
    private javax.swing.JComboBox<String> boxNomorInp;
    private javax.swing.JButton btnCetakInp;
    private javax.swing.JButton btnHapusInp;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnOrderPend;
    private javax.swing.JButton btnTambahLain;
    private javax.swing.JButton btnTambahMakan;
    private javax.swing.JButton btnTambahMinum;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinLainInp;
    private javax.swing.JSpinner spinMakanInp;
    private javax.swing.JSpinner spinMinumInp;
    private javax.swing.JTextField txtNamaInp;
    // End of variables declaration//GEN-END:variables
}
