/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafegui;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author User
 */
public class OrderPending extends javax.swing.JFrame {

    String user = "root";
    String pswd = "";
    String host = "localhost";
    String db = "cafe";
    String url = "";
    String StrSQL;
    String StrQry;
        
    private Connection Lconnection = null;
    
    public OrderPending() {
        initComponents();
        tampilTabelOrderInfo();
        btnSelesaiOrd.setEnabled(false);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            url="jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pswd;
            Lconnection = DriverManager.getConnection(url);
        }
        catch (ClassNotFoundException e){
            System.out.println("jdbc.Driver tidak ditemukan");
        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
    }
    
    private Object[][] getDataOrderInfo(){
        Object[][] dataOrderInfo = null;
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            
            url="jdbc:mysql://"+host+"/"+db+"?user="+user+"&password="+pswd;
            Connection conn = DriverManager.getConnection(url);
            
            Statement st = conn.createStatement();
            PreparedStatement pst = conn.prepareStatement("SELECT * FROM order_info", ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = pst.executeQuery();
            
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();
            
            dataOrderInfo = new Object[rowCount][7];
            int no = -1;
            
            while(rs.next()){
                no = no + 1;
                dataOrderInfo[no][0] = rs.getString("ID_Order");
                dataOrderInfo[no][1] = rs.getString("Nama_Cust");
                dataOrderInfo[no][2] = rs.getString("Jenis_Meja");
                dataOrderInfo[no][3] = rs.getString("No_Meja");
                dataOrderInfo[no][4] = rs.getString("Pesanan");
                dataOrderInfo[no][5] = rs.getString("Total_Harga");
                dataOrderInfo[no][6] = rs.getString("Status");
            }
            st.close();
            conn.close();
            
        }
        catch (ClassNotFoundException e){
            System.out.println("jdbc.Driver tidak ditemukan");
        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
        return dataOrderInfo;
    }
    
    private void tampilTabelOrderInfo(){
        String[] columnNames =
            {"ID Order", "Nama Customer", "Jenis Meja", "Nomor Meja", "Pesanan", "Total Harga", "Status"};
            JTable table = new JTable(getDataOrderInfo(), columnNames);
            scrollOrder.setViewportView(table);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        scrollOrder = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtIDOrd = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaPesanOrd = new javax.swing.JTextArea();
        txtNamaOrd = new javax.swing.JTextField();
        btnCekIDOrd = new javax.swing.JButton();
        btnCekNamaOrd = new javax.swing.JButton();
        btnSelesaiOrd = new javax.swing.JButton();
        lblNoMejaOrd = new javax.swing.JLabel();
        lblJenisOrd = new javax.swing.JLabel();
        lblTotalOrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 88, 168));

        btnKeluar.setText("Kembali");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnKeluar)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(248, 251, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel5.setBackground(new java.awt.Color(248, 251, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel21.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel21.setText("Order ID");

        jLabel22.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel22.setText("Nama Customer");

        jLabel28.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel28.setText("Jenis Meja");

        jLabel29.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel29.setText("No. Meja");

        jLabel30.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel30.setText("Total");

        jLabel31.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel31.setText("Pesanan");

        jLabel32.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel32.setText(":");

        jLabel33.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel33.setText(":");

        jLabel34.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel34.setText(":");

        jLabel35.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel35.setText(":");

        jLabel36.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel36.setText(":");

        jLabel37.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel37.setText(":");

        areaPesanOrd.setEditable(false);
        areaPesanOrd.setBackground(new java.awt.Color(255, 255, 255));
        areaPesanOrd.setColumns(20);
        areaPesanOrd.setRows(5);
        jScrollPane3.setViewportView(areaPesanOrd);

        btnCekIDOrd.setText("Cek ID");
        btnCekIDOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekIDOrdActionPerformed(evt);
            }
        });

        btnCekNamaOrd.setText("Cek Nama");
        btnCekNamaOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekNamaOrdActionPerformed(evt);
            }
        });

        btnSelesaiOrd.setText("Selesaikan");
        btnSelesaiOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiOrdActionPerformed(evt);
            }
        });

        lblNoMejaOrd.setText("-");

        lblJenisOrd.setText("-");

        lblTotalOrd.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTotalOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNoMejaOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel34)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblJenisOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(btnSelesaiOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel32)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtIDOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCekIDOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtNamaOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCekNamaOrd)))))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel32)
                    .addComponent(txtIDOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCekIDOrd))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel33)
                    .addComponent(txtNamaOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCekNamaOrd))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel34)
                    .addComponent(btnSelesaiOrd)
                    .addComponent(lblJenisOrd))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel35)
                    .addComponent(lblNoMejaOrd))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(jLabel36))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel37)
                    .addComponent(lblTotalOrd))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollOrder)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(scrollOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekIDOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekIDOrdActionPerformed
        try {
            StrSQL = "SELECT * FROM order_info WHERE ID_Order ='" + txtIDOrd.getText() + "'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaOrd.setText(rs.getString("Nama_Cust"));
                lblJenisOrd.setText(rs.getString("Jenis_Meja"));
                lblNoMejaOrd.setText(rs.getString("No_Meja"));
                areaPesanOrd.setText(rs.getString("Pesanan"));
                lblTotalOrd.setText(rs.getString("Total_Harga"));
                txtIDOrd.setText(rs.getString("ID_Order"));

                btnSelesaiOrd.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Data Tidak Ada", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnCekIDOrdActionPerformed

    private void btnCekNamaOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekNamaOrdActionPerformed
        try {
            StrSQL = "SELECT * FROM order_info WHERE Nama_Cust LIKE '%" + txtNamaOrd.getText() + "%'";
            Statement st = Lconnection.createStatement();
            ResultSet rs = st.executeQuery(StrSQL);

            if (rs.next()) {
                txtNamaOrd.setText(rs.getString("Nama_Cust"));
                lblJenisOrd.setText(rs.getString("Jenis_Meja"));
                lblNoMejaOrd.setText(rs.getString("No_Meja"));
                areaPesanOrd.setText(rs.getString("Pesanan"));
                lblTotalOrd.setText(rs.getString("Total_Harga"));
                txtIDOrd.setText(rs.getString("ID_Order"));

                btnSelesaiOrd.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Data Tidak Ada", "Informasi",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } 
        catch (SQLException e) {
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnCekNamaOrdActionPerformed

    private void btnSelesaiOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiOrdActionPerformed
        try {     
            StrSQL = "DELETE FROM order_info WHERE ID_Order = ?";
            PreparedStatement pStatement = Lconnection.prepareStatement(StrSQL);

            pStatement.setString(1, txtIDOrd.getText());
            

            if (pStatement.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(this, "Delete sukses", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Delete gagal", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();
        }
        catch (SQLException e) {
            System.out.println("koneksi gagal " + e.toString());
        }
        
        try{
            StrQry = "INSERT INTO history_info (Nama_Cust, Jenis_Meja, No_Meja, Pesanan, Total_Harga, Status)"
                   + "VALUES (?,?,?,?,?,?)";
        
            PreparedStatement pStatement = Lconnection.prepareStatement(StrQry);

            pStatement.setString(1, txtNamaOrd.getText());
            pStatement.setString(2, lblJenisOrd.getText());
            pStatement.setString(3, lblNoMejaOrd.getText());
            pStatement.setString(4, areaPesanOrd.getText());
            pStatement.setString(5, lblTotalOrd.getText());
            pStatement.setString(6, "Completed");

            if (pStatement.executeUpdate()>0){
                JOptionPane.showMessageDialog(this,
                    "Penambahan sukses", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,
                    "Penambahan gagal", "Informasi",
                    JOptionPane.INFORMATION_MESSAGE);
            }

            pStatement.close();
            

        }
        catch (SQLException e){
            System.out.println("Koneksi gagal" + e.toString());
        }
    }//GEN-LAST:event_btnSelesaiOrdActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        this.dispose();
        new InputOrder().setVisible(true);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderPending.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderPending().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaPesanOrd;
    private javax.swing.JButton btnCekIDOrd;
    private javax.swing.JButton btnCekNamaOrd;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSelesaiOrd;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblJenisOrd;
    private javax.swing.JLabel lblNoMejaOrd;
    private javax.swing.JLabel lblTotalOrd;
    private javax.swing.JScrollPane scrollOrder;
    private javax.swing.JTextField txtIDOrd;
    private javax.swing.JTextField txtNamaOrd;
    // End of variables declaration//GEN-END:variables
}
